---
- name: creating users on group of servers
  hosts: webserver
  tasks: 
    - name: creating users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
...
