---
- name: installing tomcat on all the servers
  hosts: all 
  tasks: 
    - name: installing tomcat
      apt: 
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items: 
        - tomcat10
        - tomcat10-admin
      tags: installation
    - name: copying the passwd file on all the servers
      copy: 
        src: /etc/passwd
        dest: /tmp
...
